### ISSUE TITLE
New Problem with "Could not resolve type id 'weather' as a subtype of"

### ISSUE THREAD

**Issue by focusbbs** [theyellow/pogorobot#51]
Hello, a new issue apears: "Could not resolve type id 'weather' as a subtype of" it is a RDM Feature:

`WARN DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Could not resolve type id 'weather' as a subtype of [simple type, class pogorobot.rocketmap.messages.IncomingEvent<pogorobot.events.EventMessage<java.lang.Object>>]: known type ids = [egg, gym, gym_details, invasion, pokemon, pokestop, quest, raid]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'weather' as a subtype of [simple type, class pogorobot.rocketmap.messages.IncomingEvent<pogorobot.events.EventMessage<java.lang.Object>>]: known type ids = [egg, gym, gym_details, invasion, pokemon, pokestop, quest, raid]`

**Comment by theyellow** [comment]
Weather as a new message type should be implemented, so this noise in logs is away...
