### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by Swiss-Rainbow** [theyellow/pogorobot#55]
HI 

1. if you do docker down you shouldn't clean the DB.
2. Use your own stickers in the config.
3. Infobox that is always shown below who has agreed to which raid.

**Comment by theyellow** [comment]
1. "docker down" removes containers (don't know why, i'm no expert)
    -> docker stop
    -> Sufficient?
2. stickers are one of the things i'm working on 
3. like "RaidSum" ?

**Comment by Swiss-Rainbow** [comment]
3. Yes    
![grafik](https://user-images.githubusercontent.com/38362961/106949638-80fa2b00-672d-11eb-9fbf-ae72e99e689c.png)

**Comment by theyellow** [comment]
1. fixed 
2. fixed (in config you should use alternativeStickers = true) 
3. same as #56
